#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

# mknod foo c 5 1
mknod /dev/null c 1 3
chmod 666 /dev/null
mkdir tmp

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

exec /bin/sh
